#QUESTION A

In [25]:
import numpy as np  

In [26]:
m = int(input("enter number of rows:"))  
n = int(input("enter number of columns:"))

enter number of rows:4
enter number of columns:4


In [28]:
print("enter elements separated by a space: ")  
print("elements of matrix A")
A = list(map(int, input().split())) 

Mtx_A= np.array(A).reshape(m, n)

print("elements of matrix B")
B = list(map(int, input().split()))  
Mtx_B= np.array(B).reshape(m, n)

enter elements separated by a space: 
elements of matrix A
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
elements of matrix B
11 22 33 44 55 66 77 88 99 10 11 12 13 14 15 16


MATRIX A

In [29]:

 print(Mtx_A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


MATRIX B

In [30]:
 print(Mtx_B)

[[11 22 33 44]
 [55 66 77 88]
 [99 10 11 12]
 [13 14 15 16]]


1. DOT PRODUCT

In [31]:
np.dot(Mtx_A,Mtx_B)

array([[ 470,  240,  280,  320],
       [1182,  688,  824,  960],
       [1894, 1136, 1368, 1600],
       [2606, 1584, 1912, 2240]])

2. TRANSPOSE

In [32]:
np.transpose(Mtx_A)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

3. TRACE

In [33]:
np.trace(Mtx_A)

34

4. RANK

In [34]:
np.linalg.matrix_rank(Mtx_A)

2

5. DETERMINANT

In [35]:
np.linalg.det(Mtx_A)

0.0